[package]
name = "nes-utils-cli"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
nes-utils = "0.1.0"
structopt = "0.3.26"
